
services:
  app:
    container_name: travel-app
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DJANGO_SETTINGS_MODULE=travel.settings.prod
    volumes:
      - travel-media:/app/media
    command: >
      bash -c "
        python manage.py migrate &&
        python manage.py runserver 0.0.0.0:8000
      "
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - travel-rt-network

  postgres:
    image: postgres:17
    container_name: travel-postgres
    volumes:
      - travel-postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    restart: unless-stopped
    networks:
      - travel-rt-network

volumes:
  travel-redis:
  travel-postgres:
  travel-media:

networks:
  travel-rt-network:
    name: travel-rt-network
    driver: bridge
    external: true
