x-app-base: &app-base
  build:
    context: .
    dockerfile: Dockerfile
  volumes:
    - .:/app
  depends_on:
    postgres:
      condition: service_healthy
    redis:
      condition: service_started
  environment: &common-env
    POSTGRES_HOST: postgres
    CELERY_BROKER_URL: redis://redis:6379/0
    CELERY_RESULT_BACKEND: redis://redis:6379/0
  env_file:
    - .env
  restart: unless-stopped

services:
#  app:
#    <<: *app-base
#    container_name: travel-app
#    command: python manage.py runserver 0.0.0.0:8000
#    ports:
#      - "8000:8000"
#
#  celery:
#    <<: *app-base
#    container_name: travel-celery
#    command: celery -A travel worker -l info
#    depends_on:
#      postgres:
#        condition: service_healthy
#      redis:
#        condition: service_started

  postgres:
    image: postgres:17
    container_name: travel-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - travel-postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-postgres}"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: travel-redis
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - travel-redis:/data
    restart: unless-stopped

volumes:
  travel-redis:
  travel-postgres:
