# Generated by Django 5.1.7 on 2025-05-03 15:40

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Router',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('short_description', models.TextField(verbose_name='Краткое описание')),
                ('full_description', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Полное описание')),
                ('image', models.ImageField(blank=True, help_text='Загрузите изображение для маршрута', null=True, upload_to='routers/images/', verbose_name='Изображение')),
                ('duration', models.DurationField(help_text='Укажите продолжительность маршрута в формате ЧЧ:ММ:СС', verbose_name='Продолжительность маршрута')),
                ('difficulty', models.CharField(choices=[('easy', 'Легкий'), ('medium', 'Средний'), ('hard', 'Сложный')], default='medium', help_text='Выберите уровень сложности маршрута', max_length=10, verbose_name='Сложность')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routers', to='locations.district', verbose_name='Район')),
                ('settlement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routers', to='locations.settlement', verbose_name='Населённый пункт')),
            ],
            options={
                'verbose_name': 'Маршрут',
                'verbose_name_plural': 'Маршруты',
                'ordering': ['title'],
            },
        ),
    ]
