# Generated by Django 5.1.7 on 2026-03-19 02:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='router',
            name='creation_method',
            field=models.CharField(choices=[('manual', 'Вручную'), ('ai_generated', 'Сгенерирован ИИ')], default='manual', max_length=20, verbose_name='Способ создания'),
        ),
        migrations.CreateModel(
            name='RouteGenerationJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='ID задачи')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('processing', 'В обработке'), ('completed', 'Завершён'), ('failed', 'Ошибка')], default='pending', max_length=20, verbose_name='Статус')),
                ('result', models.JSONField(blank=True, null=True, verbose_name='Результат LLM')),
                ('error_message', models.TextField(blank=True, verbose_name='Сообщение об ошибке')),
                ('intent', models.JSONField(blank=True, null=True, verbose_name='Intent (параметры запроса)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('router', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generation_job', to='routers.router', verbose_name='Созданный маршрут')),
            ],
            options={
                'verbose_name': 'Задача генерации маршрута',
                'verbose_name_plural': 'Задачи генерации маршрутов',
                'ordering': ['-created_at'],
            },
        ),
    ]
