# Generated by Django 5.1.7 on 2026-03-18 22:05

import django.db.models.deletion
import django.utils.timezone
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


def copy_created_at_to_published_at(apps, schema_editor):
    News = apps.get_model('news', 'News')
    News.objects.update(published_at=models.F('created_at'))


def copy_published_at_to_created_at(apps, schema_editor):
    News = apps.get_model('news', 'News')
    News.objects.update(created_at=models.F('published_at'))


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='creation_method',
            field=models.CharField(choices=[('manual', 'Вручную'), ('parsing', 'Парсинг')], default='manual', max_length=20, verbose_name='Способ создания'),
        ),
        migrations.AddField(
            model_name='news',
            name='published_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публикации'),
        ),
        migrations.RunPython(copy_created_at_to_published_at, copy_published_at_to_created_at),
        migrations.AlterField(
            model_name='news',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Содержание'),
        ),
        migrations.AlterField(
            model_name='news',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='news',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Создано пользователем'),
        ),
        migrations.AlterField(
            model_name='news',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='news_images/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Заголовок'),
        ),
    ]
