# Generated by Django 5.1.7 on 2025-04-29 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название района')),
            ],
            options={
                'verbose_name': 'Район',
                'verbose_name_plural': 'Районы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('type', models.CharField(choices=[('city', 'Город'), ('town', 'Посёлок городского типа'), ('village', 'Село'), ('village_hamlet', 'Деревня')], default='city', max_length=20, verbose_name='Тип населённого пункта')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settlements', to='locations.district', verbose_name='Район')),
            ],
            options={
                'verbose_name': 'Населённый пункт',
                'verbose_name_plural': 'Населённые пункты',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='district',
            name='administrative_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='governed_districts', to='locations.settlement', verbose_name='Административный центр'),
        ),
    ]
